### Add Report
POST http://localhost:3000/reports
content-type: application/json

{
    "make": "dodge",
    "model": "viper",
    "year": 1990,
    "lng": 15,
    "lat": 15,
    "mileage": 150000,
    "price": 300000
}   

### Approve Report
PATCH http://localhost:3000/reports/4
content-type: application/json

{
    "approved": true
}   


### Get Estimate
GET http://localhost:3000/reports?make=toyota&model=viper&year=1980&lng=15&lat=15&mileage=150000&price=300000
content-type: application/json
