### Sign Up (Create New User)
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "kj4@gmail.com",
  "password": "dupadupa4"
}   

### Sign in (Login - Authenticate User and Get Session)
POST http://localhost:3000/auth/signin
content-type: application/json

{
  "email": "kj@gmail.com",
  "password": "dupadupa"
}   

### Sign Out (Destroy Session)
POST http://localhost:3000/auth/signout

### Check if session is working (Get Current User)
GET http://localhost:3000/auth/whoami

----------------------------------------------------------------------------------------

### Get User by id
GET http://localhost:3000/auth/4 


### Get Users with email
GET http://localhost:3000/auth?email=test@example.com


### Delete User by id
DELETE  http://localhost:3000/auth/3


### Update User by id
PATCH http://localhost:3000/auth/3
content-type: application/json

{
  "password": "nowehaslo"
  //"email": "test@test.com.pl"
}  

